# Generated by Django 4.2.2 on 2023-06-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_speaker_alter_client_options_topic_speaker_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="topic",
            new_name="title",
        ),
        migrations.AddField(
            model_name="client",
            name="nik_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="UserName"
            ),
        ),
        migrations.RemoveField(
            model_name="topic",
            name="speaker",
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag", models.BooleanField(default=False, null=True)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers_flag",
                        to="bot.speaker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Флаг",
                "verbose_name_plural": "Флаги",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, null=True, verbose_name="Title"),
                ),
                ("text", models.TextField()),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.speaker"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="speaker",
            field=models.ManyToManyField(to="bot.speaker"),
        ),
    ]
