# Generated by Django 4.2.2 on 2023-06-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_rename_topic_topic_title_client_nik_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="speaker",
        ),
        migrations.RemoveField(
            model_name="event",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="speaker",
        ),
        migrations.AddField(
            model_name="speaker",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.event",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.event",
            ),
        ),
    ]
