# Generated by Django 4.2.2 on 2023-06-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_remove_event_speaker_remove_event_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="bot.event",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="bot.event",
            ),
        ),
    ]
