# Generated by Django 4.2.2 on 2023-06-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0013_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="topic"
            ),
        ),
        migrations.CreateModel(
            name="ApplicationSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, null=True, verbose_name="Name"),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="topic"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers_application",
                        to="bot.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка в спикеры",
                "verbose_name_plural": "Заявки в спикеры",
            },
        ),
    ]
