# Generated by Django 4.2.2 on 2023-06-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0015_topic_speaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="speaker",
        ),
        migrations.AddField(
            model_name="speaker",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers_topic",
                to="bot.topic",
            ),
        ),
    ]
