# Generated by Django 4.2.2 on 2023-06-24 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0016_remove_topic_speaker_speaker_speaker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speaker",
            old_name="speaker",
            new_name="topic",
        ),
    ]
