# Generated by Django 4.2.2 on 2023-06-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0017_rename_speaker_speaker_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="event",
        ),
        migrations.AddField(
            model_name="speaker",
            name="event",
            field=models.ManyToManyField(to="bot.event"),
        ),
    ]
