# Generated by Django 4.2.2 on 2023-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0019_alter_topic_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="topic",
        ),
        migrations.AddField(
            model_name="speaker",
            name="topic",
            field=models.ManyToManyField(to="bot.topic"),
        ),
    ]
