# Generated by Django 4.2.2 on 2023-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0020_remove_speaker_topic_speaker_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="event",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="topic",
        ),
        migrations.AddField(
            model_name="event",
            name="speaker",
            field=models.ManyToManyField(to="bot.speaker"),
        ),
        migrations.AddField(
            model_name="event",
            name="topic",
            field=models.ManyToManyField(to="bot.topic"),
        ),
    ]
