# Generated by Django 4.2.2 on 2023-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0021_remove_speaker_event_remove_topic_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="topic",
        ),
        migrations.AddField(
            model_name="topic",
            name="time_event",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
